services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: project_spe_web
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
