services:
  db:
    env_file: ".env"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql

  db_test:
    env_file: ".env.test"
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - dbtestdata:/var/lib/mysql

volumes:
  mysqldata:
  dbtestdata:
